### ISSUE TITLE
Separate java-jdbi3 module?

### ISSUE THREAD

**Issue by sjoerdtalsma** [opentracing-contrib/java-jdbi#16]
Should we make this contrib repo a multi-module repository to release separate
- `jdbi-opentracing` and
- `jdbi3-opentracing` 

maven artifacts?

The split package structure kind of feels 'wrong' and I think having JDBI as **provided** dependency also feels wrong. JDBI is a transient dependency for this module and ought to be declared as such.

I'm willing to create a PR for this if there is demand for it.

**Comment by malafeev** [comment]
@sjoerdtalsma PR would be nice

**Comment by malafeev** [comment]
Probably better names:
`opentracing-jdbi`
`opentracing-jdbi3`

**Comment by sjoerdtalsma** [comment]
Do you want me to incorporate #17 and #18 in a single PR?
Alternatively I can do follow-up PR's but they would have to depend on the one for #16

**Comment by malafeev** [comment]
please make a single PR.

**Comment by sjoerdtalsma** [comment]
> please make a single PR.

Ok :+1:
