### ISSUE TITLE
JDBI3: Replace TimingCollector by SqlLogger if available

### ISSUE THREAD

**Issue by sjoerdtalsma** [opentracing-contrib/java-jdbi#18]
JDBI3 deprecated the use of its `TimingCollector`.

I created a `OpenTracingSqlLogger` on the same principle as the current timing collector and have the following code in my JDBI3 plugin:

```java
public class OpentracingJdbi3Plugin implements JdbiPlugin {
    private static final Logger LOGGER = Logger.getLogger(OpentracingJdbi3Plugin.class.getName());

    @Override
    public void customizeJdbi(Jdbi jdbi) {
        try {
            OpentracingSqlLogger.configure(jdbi);
        } catch (LinkageError sqlLoggerApiUnavailable) {
            LOGGER.log(Level.WARNING, sqlLoggerApiUnavailable,
                    () -> "Could not configure Opentracing SqlLogger implementation. " +
                            "Are you using JDBI version 3.2 or greater?");
            OpentracingTimingCollector.configure(jdbi);
        }
    }
```

As you can see it uses the new `SqlLogger` JDBI3 api if available but falls back on the (deprecated) `TimingCollector` variant without using reflection.

**Comment by sjoerdtalsma** [comment]
Contrary to what the name suggests, the _current_ OpenTracingCollector **already is** a `SqlLogger`.

As my change for #19 was already a breaking change, I decided to add a deprecated `OpentracingTimingCollector` and renamed the current implementation to `OpentracingSqlLogger` which better represents what it is and avoids confusion between these two implementations.

So this issue should be fixed if the PR above gets merged.

**Comment by malafeev** [comment]
PR merged.
