### ISSUE TITLE
Created span is not in scope

### ISSUE THREAD

**Issue by hypnoce** [opentracing-contrib/java-jdbi#9]
Hi all,

I was looging at the code and noticed that in [OpenTracingCollector.java#L101](https://github.com/opentracing-contrib/java-jdbi/blob/e9a13c65cfb363e9407acaaab2aa228d806ac861/src/main/java/io/opentracing/contrib/jdbi/OpenTracingCollector.java#L101), the span is started but not put in scope.

I have a use case where we are developping a jdbc driver with native opentracing support. Therefore, when a span is created and started in the driver, it does not register as a child of the jdbi span.

Does it make sense to you to have the jdbi span in scope ?

Thanks and great work !

**Comment by malafeev** [comment]
span is started in line 101 and finished in line 110.
If we put it in scope in line 101 then in line 110 we will remove it from scope.
Scope must be closed (span is finished).

**Comment by hypnoce** [comment]
I just realised that the method only collects the elapsed time and do not wrap the actual execution.
